// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpOportunidades.Infrastructure;

namespace WpOportunidades.Infrastructure.Migrations
{
    [DbContext(typeof(WpOportunidadesContext))]
    [Migration("20180906194659_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WpOportunidades.Entities.Endereco", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<string>("Bairro");

                    b.Property<string>("CEP");

                    b.Property<string>("Cidade");

                    b.Property<string>("Complemento");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<DateTime>("DataEdicao");

                    b.Property<string>("Descricao");

                    b.Property<string>("Estado");

                    b.Property<int>("IdCliente");

                    b.Property<string>("Local");

                    b.Property<string>("Nome");

                    b.Property<int>("NumeroLocal");

                    b.Property<int>("OportunidadeId");

                    b.Property<int>("Status");

                    b.Property<int>("UsuarioCriacao");

                    b.Property<int>("UsuarioEdicao");

                    b.HasKey("ID");

                    b.HasIndex("OportunidadeId")
                        .IsUnique();

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("WpOportunidades.Entities.Oportunidade", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<DateTime>("DataEdicao");

                    b.Property<DateTime>("DataOportunidade");

                    b.Property<string>("Descricao");

                    b.Property<TimeSpan>("HoraFim");

                    b.Property<TimeSpan>("HoraInicio");

                    b.Property<int>("IdCliente");

                    b.Property<string>("Nome");

                    b.Property<int>("Quantidade");

                    b.Property<int>("Status");

                    b.Property<int>("UsuarioCriacao");

                    b.Property<int>("UsuarioEdicao");

                    b.Property<decimal>("Valor");

                    b.HasKey("ID");

                    b.ToTable("Oportunidades");
                });

            modelBuilder.Entity("WpOportunidades.Entities.Endereco", b =>
                {
                    b.HasOne("WpOportunidades.Entities.Oportunidade", "Oportunidade")
                        .WithOne("Endereco")
                        .HasForeignKey("WpOportunidades.Entities.Endereco", "OportunidadeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
